//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seminar_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDon
    {
        public int MaCTD { get; set; }
        public int MaD { get; set; }
        public int MaSP { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public string TenSP { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual Don Don { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
