//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seminar_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDons = new HashSet<ChiTietDon>();
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public int MaLoaiSP { get; set; }
        public int SoLuongTon { get; set; }
        public decimal Gia { get; set; }
        public string MoTaSP { get; set; }
        public string HinhAnh { get; set; }
        public int MaNguoiBan { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDon> ChiTietDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
